// <auto-generated />
using System;
using JwtAuthWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JwtAuthWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241212050852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("JwtAuthWebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "$2a$11$ycHRAsTG3Oj1UZfY4D19g.G4CUrXUpj7fXbqlHZcweU0SjmFZmp/e",
                            Username = "adi"
                        },
                        new
                        {
                            Id = 2,
                            Password = "$2a$11$AT3zOO4jNjnYY5DlSeSRW.idzdZ7z.KWyDhhjnjmWQDdTj0wbi4r6",
                            Username = "budi"
                        },
                        new
                        {
                            Id = 3,
                            Password = "$2a$11$ukCGM.Gmu0Fv9om5Ee3H6ewK5TMKGFhQlLJuGUY1Ywz/HqPWpVmY.",
                            Username = "caca"
                        });
                });

            modelBuilder.Entity("JwtAuthWebApi.Entities.UserDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_details");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_details_user_id");

                    b.ToTable("user_details", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Adi Wibowo",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2002, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Budi Darwan",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1998, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Caca Handika",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("JwtAuthWebApi.Entities.UserDetail", b =>
                {
                    b.HasOne("JwtAuthWebApi.Entities.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("JwtAuthWebApi.Entities.UserDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_details_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JwtAuthWebApi.Entities.User", b =>
                {
                    b.Navigation("UserDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
